name: Test Python Scripts

on:
  push:
  #   branches: [ main ]
    paths:
      - src/**
      - tests/**
      - .github/workflows/test-python.yml
  pull_request:
  #   branches: [ main ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.repository }}-test-python
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for potential version/tag operations

    # - name: Install pandoc
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y pandoc texlive-base
    #     pandoc --version  # Verify installation

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov
        pip install -e '.[test]'  # Install package in editable mode with test dependencies
  
    - name: Run tests
      run: |
        pytest tests/ -v --cov=scripts

    - name: Print coverage report
      run: |
        coverage report
